import sys
import icons.icons_rc
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(210, 190)
        MainWindow.setMaximumSize(QtCore.QSize(240, 210))
        MainWindow.setStyleSheet("*{\n"
"    color:white;\n"
"    background:none;\n"
"    background-color:transparent;\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    border:none;\n"
"}\n"
"\n"
"#bottomFrameContainer{\n"
"    background-color:#0F0E0E;\n"
"    border-bottom-left-radius:15px;\n"
"    border-bottom-right-radius:15px;\n"
"}\n"
"\n"
"#topFrameContainer{\n"
"    border-top-left-radius:15px;\n"
"    border-top-right-radius:15px;\n"
"    background-color:#d63031;\n"
"}\n"
"QMenu{\n"
    "background-color: rgb(0, 0, 0);\n"
    "color: rgb(255, 255, 255);\n"
"}"
"QMenu::item:selected{\n"
    "background-color: rgb(255, 255, 255);\n"
    "color: rgb(0, 0, 0)\n;"
"}\n"
"QInputDialog{background-color:#000; color:#000}\n"
)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topFrameContainer = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFrameContainer.sizePolicy().hasHeightForWidth())
        self.topFrameContainer.setSizePolicy(sizePolicy)
        self.topFrameContainer.setStyleSheet("")
        self.topFrameContainer.setObjectName("topFrameContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.topFrameContainer)
        self.verticalLayout.setContentsMargins(9, 5, 9, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topFrame = QtWidgets.QFrame(self.topFrameContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topFrame.sizePolicy().hasHeightForWidth())
        self.topFrame.setSizePolicy(sizePolicy)
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.topFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.coinPrice = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coinPrice.sizePolicy().hasHeightForWidth())
        self.coinPrice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.coinPrice.setFont(font)
        self.coinPrice.setObjectName("coinPrice")
        self.verticalLayout_3.addWidget(self.coinPrice, 0, QtCore.Qt.AlignVCenter)
        self.coinOtherPrice = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coinOtherPrice.sizePolicy().hasHeightForWidth())
        self.coinOtherPrice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.coinOtherPrice.setFont(font)
        self.coinOtherPrice.setObjectName("coinOtherPrice")
        self.verticalLayout_3.addWidget(self.coinOtherPrice, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.topFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.coinImage = QtWidgets.QPushButton(self.frame_2)
        self.coinImage.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/btc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coinImage.setIcon(icon)
        self.coinImage.setIconSize(QtCore.QSize(60, 60))
        self.coinImage.setObjectName("coinImage")
        self.horizontalLayout_4.addWidget(self.coinImage, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.topFrame)
        self.marketNameLabel = QtWidgets.QLabel(self.topFrameContainer)
        self.marketNameLabel.setObjectName("marketNameLabel")
        self.verticalLayout.addWidget(self.marketNameLabel, 0, QtCore.Qt.AlignLeft)
        self.midleFrame = QtWidgets.QFrame(self.topFrameContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.midleFrame.sizePolicy().hasHeightForWidth())
        self.midleFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.midleFrame.setFont(font)
        self.midleFrame.setStyleSheet("color:#FFF;")
        self.midleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.midleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.midleFrame.setObjectName("midleFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.midleFrame)
        self.horizontalLayout.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.up24hLabel = QtWidgets.QLabel(self.midleFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.up24hLabel.setFont(font)
        self.up24hLabel.setObjectName("up24hLabel")
        self.horizontalLayout.addWidget(self.up24hLabel)
        self.up24hValue = QtWidgets.QLabel(self.midleFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.up24hValue.setFont(font)
        self.up24hValue.setObjectName("up24hValue")
        self.horizontalLayout.addWidget(self.up24hValue, 0, QtCore.Qt.AlignLeft)
        self.down24hDown = QtWidgets.QLabel(self.midleFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.down24hDown.setFont(font)
        self.down24hDown.setObjectName("down24hDown")
        self.horizontalLayout.addWidget(self.down24hDown, 0, QtCore.Qt.AlignRight)
        self.down24hValue = QtWidgets.QLabel(self.midleFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.down24hValue.setFont(font)
        self.down24hValue.setObjectName("down24hValue")
        self.horizontalLayout.addWidget(self.down24hValue, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.midleFrame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.topFrameContainer)
        self.bottomFrameContainer = QtWidgets.QFrame(self.centralwidget)
        self.bottomFrameContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomFrameContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrameContainer.setObjectName("bottomFrameContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bottomFrameContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalFrame = QtWidgets.QFrame(self.bottomFrameContainer)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.coinNameLabel = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.coinNameLabel.setFont(font)
        self.coinNameLabel.setObjectName("coinNameLabel")
        self.horizontalLayout_2.addWidget(self.coinNameLabel)
        self.change24h = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change24h.sizePolicy().hasHeightForWidth())
        self.change24h.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-sort-up-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change24h.setIcon(icon1)
        self.change24h.setIconSize(QtCore.QSize(18, 18))
        self.change24h.setObjectName("change24h")
        self.horizontalLayout_2.addWidget(self.change24h, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addWidget(self.horizontalFrame)
        self.timeLabel = QtWidgets.QLabel(self.bottomFrameContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(False)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout_5.addWidget(self.timeLabel)
        self.verticalLayout_2.addWidget(self.bottomFrameContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.coinPrice.setText(_translate("MainWindow", "$ 12,452.63"))
        self.coinOtherPrice.setText(_translate("MainWindow", "MKCAP 798.9 B"))
        self.marketNameLabel.setText(_translate("MainWindow", "CoinBase"))
        self.up24hLabel.setText(_translate("MainWindow", "24h ↑"))
        self.up24hValue.setText(_translate("MainWindow", "13,198"))
        self.down24hDown.setText(_translate("MainWindow", "24h ↓"))
        self.down24hValue.setText(_translate("MainWindow", "10,826"))
        self.coinNameLabel.setText(_translate("MainWindow", "BTC Bitcoin"))
        self.change24h.setText(_translate("MainWindow", " 2.9%"))
        self.timeLabel.setText(_translate("MainWindow", "23:10 Tue, 09.07.19 (GMT+3)"))